@startuml
/' Casos de usos do sistema universidade'/
left to right direction
actor Aluno as a


package Funcionarios {
  actor Professor as prof
  actor Coordenador as cor
  actor Caixa as cx
  actor Atendente as at

  actor Diretor as d
}
package Universidade {
  usecase "Sala de aula" as UC1
  usecase "Laboratorio de informatica" as UC2
  usecase "Biblioteca" as UC3
  usecase "Cantina" as UC5
  usecase "Financeiro e matriculas" as UC4
  
}
a <--> UC4
a -- UC1
a -- UC2
a -- UC3
a -- UC5
at -- UC4
at -- UC5
a -- prof
prof -- UC1
prof -- UC2
prof -- UC3
cor -- prof
cor -- a
cx -- UC4
d --> Universidade
@enduml